### ISSUE TITLE
I hate spam

### ISSUE THREAD

**Issue by thelfensdrfer** [DashboardHero/uikit#1]

**Comment by thelfensdrfer** [comment]
For reference, this was the mail:

```
Hello fellow developer,

Have been working on a spinoff of UI Kit https://getuikit.com/ , with web components. Would love to get your expert opinion on it:

https://github.com/DashboardHero/uikit (MIT license)

Do you find it easier to use? Do you find this useful? Would you use it in your projects?
If the answer is yes for any of the above, would greatly appreciate a star from you.

Talk soon,
Mike
```

On the unsubscribe page even was a link to getuikit.com. Was it copied or are you in any way working together?

<img width="293" alt="Screenshot 2020-01-28 at 11 15 00" src="https://user-images.githubusercontent.com/699106/73254876-825e5280-41bf-11ea-9b09-6282d2f8ed78.png">

**Comment by DashboardHero** [comment]
Hello Tim,

Thanks for letting me know.
Sorry for this - no, not working with UI Kit. I paid a marketing company to help gain visibility on my repository. Calling them now, and will get back to you.
